"""add transfer_snapshots table

Revision ID: 3612def62e6e
Revises: b08a00b1c327
Create Date: 2026-03-31 14:31:24.699416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3612def62e6e'
down_revision: Union[str, Sequence[str], None] = 'b08a00b1c327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transfers_in_event', sa.Integer(), server_default='0', nullable=False),
    sa.Column('transfers_out_event', sa.Integer(), server_default='0', nullable=False),
    sa.Column('net_transfers', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'recorded_at', name='uq_transfer_snap_player_ts')
    )
    op.create_index('idx_transfer_snap_player', 'transfer_snapshots', ['player_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transfer_snap_player', table_name='transfer_snapshots')
    op.drop_table('transfer_snapshots')
    # ### end Alembic commands ###
