"""add transfer and ownership fields to players

Revision ID: 87cdff486ad2
Revises: 0da7ffef485e
Create Date: 2026-03-26 14:54:48.056529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87cdff486ad2'
down_revision: Union[str, Sequence[str], None] = '0da7ffef485e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('selected_by_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    op.add_column('players', sa.Column('transfers_in_event', sa.Integer(), server_default='0', nullable=False))
    op.add_column('players', sa.Column('transfers_out_event', sa.Integer(), server_default='0', nullable=False))
    op.add_column('players', sa.Column('cost_change_event', sa.SmallInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'cost_change_event')
    op.drop_column('players', 'transfers_out_event')
    op.drop_column('players', 'transfers_in_event')
    op.drop_column('players', 'selected_by_percent')
    # ### end Alembic commands ###
