"""replace player_gw_xg with player_season_xg

Revision ID: 8d2b1b59b9de
Revises: fb7e8c7601cf
Create Date: 2026-03-26 10:55:52.322843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2b1b59b9de'
down_revision: Union[str, Sequence[str], None] = 'fb7e8c7601cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_xg',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=4), nullable=False),
    sa.Column('understat_id', sa.Integer(), nullable=False),
    sa.Column('games', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('minutes', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('xg', sa.Numeric(precision=7, scale=2), server_default='0', nullable=False),
    sa.Column('xa', sa.Numeric(precision=7, scale=2), server_default='0', nullable=False),
    sa.Column('xgi', sa.Numeric(precision=7, scale=2), server_default='0', nullable=False),
    sa.Column('npxg', sa.Numeric(precision=7, scale=2), server_default='0', nullable=False),
    sa.Column('shots', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('key_passes', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('xg_chain', sa.Numeric(precision=7, scale=2), server_default='0', nullable=False),
    sa.Column('xg_buildup', sa.Numeric(precision=7, scale=2), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season'),
    sa.UniqueConstraint('player_id', 'season', name='uq_xg_player_season')
    )
    op.drop_index(op.f('idx_xg_player_gw'), table_name='player_gw_xg')
    op.drop_table('player_gw_xg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_gw_xg',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gameweek_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fixture_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('xg', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('xa', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('xgi', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('npxg', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('shots', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False),
    sa.Column('key_passes', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False),
    sa.Column('shots_in_box', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False),
    sa.Column('xg_chain', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('xg_buildup', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('player_gw_xg_fixture_id_fkey')),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], name=op.f('player_gw_xg_gameweek_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('player_gw_xg_player_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('player_gw_xg_pkey'))
    )
    op.create_index(op.f('idx_xg_player_gw'), 'player_gw_xg', ['player_id', 'gameweek_id'], unique=False)
    op.drop_table('player_season_xg')
    # ### end Alembic commands ###
