"""add code field to players and teams

Revision ID: 9945ad542039
Revises: 87cdff486ad2
Create Date: 2026-03-26 16:08:18.602722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9945ad542039'
down_revision: Union[str, Sequence[str], None] = '87cdff486ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('code', sa.Integer(), server_default='0', nullable=False))
    op.add_column('teams', sa.Column('code', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'code')
    op.drop_column('players', 'code')
    # ### end Alembic commands ###
