"""add core models

Revision ID: ae6f98875242
Revises: 
Create Date: 2026-03-26 09:50:41.181753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6f98875242'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('deadline_time', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_next', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_finished', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_double', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_blank', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('average_entry_score', sa.SmallInteger(), nullable=True),
    sa.Column('highest_score', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('strength_overall_home', sa.SmallInteger(), nullable=False),
    sa.Column('strength_overall_away', sa.SmallInteger(), nullable=False),
    sa.Column('strength_attack_home', sa.SmallInteger(), nullable=False),
    sa.Column('strength_attack_away', sa.SmallInteger(), nullable=False),
    sa.Column('strength_defence_home', sa.SmallInteger(), nullable=False),
    sa.Column('strength_defence_away', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(), nullable=True),
    sa.Column('started', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('finished', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('finished_provisional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('home_goals', sa.SmallInteger(), nullable=True),
    sa.Column('away_goals', sa.SmallInteger(), nullable=True),
    sa.Column('home_difficulty', sa.SmallInteger(), nullable=True),
    sa.Column('away_difficulty', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fixtures_gw', 'fixtures', ['gameweek_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('understat_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('web_name', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('second_name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('now_cost', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=1), server_default='a', nullable=False),
    sa.Column('chance_of_playing_next_round', sa.SmallInteger(), nullable=True),
    sa.Column('news', sa.Text(), nullable=True),
    sa.Column('is_penalty_taker', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_set_piece_taker', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_form_cache',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gw_window', sa.SmallInteger(), nullable=False),
    sa.Column('total_points', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('pts_per_game', sa.Numeric(precision=4, scale=2), server_default='0', nullable=False),
    sa.Column('pts_per_90', sa.Numeric(precision=4, scale=2), server_default='0', nullable=False),
    sa.Column('xgi_per_90', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('goals', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('assists', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('bonus', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('bps_avg', sa.Numeric(precision=5, scale=1), server_default='0', nullable=False),
    sa.Column('minutes_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('clean_sheets', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'gw_window')
    )
    op.create_index('idx_form_player', 'player_form_cache', ['player_id'], unique=False)
    op.create_table('player_gw_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('goals_scored', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('assists', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('clean_sheets', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('goals_conceded', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('own_goals', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('penalties_saved', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('penalties_missed', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('yellow_cards', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('red_cards', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('saves', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('bonus', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('bps', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('influence', sa.Numeric(precision=6, scale=1), server_default='0', nullable=False),
    sa.Column('creativity', sa.Numeric(precision=6, scale=1), server_default='0', nullable=False),
    sa.Column('threat', sa.Numeric(precision=6, scale=1), server_default='0', nullable=False),
    sa.Column('ict_index', sa.Numeric(precision=6, scale=1), server_default='0', nullable=False),
    sa.Column('total_points', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('transfers_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('transfers_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('selected_by_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('value', sa.SmallInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pgw_gw', 'player_gw_stats', ['gameweek_id'], unique=False)
    op.create_index('idx_pgw_player_gw', 'player_gw_stats', ['player_id', 'gameweek_id'], unique=False)
    op.create_table('player_gw_xg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('xg', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('xa', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('xgi', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('npxg', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('shots', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('key_passes', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('shots_in_box', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('xg_chain', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('xg_buildup', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_xg_player_gw', 'player_gw_xg', ['player_id', 'gameweek_id'], unique=False)
    op.create_table('player_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('cost', sa.SmallInteger(), nullable=False),
    sa.Column('transfers_in_event', sa.Integer(), server_default='0', nullable=False),
    sa.Column('transfers_out_event', sa.Integer(), server_default='0', nullable=False),
    sa.Column('selected_by_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prices_player', 'player_prices', ['player_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prices_player', table_name='player_prices')
    op.drop_table('player_prices')
    op.drop_index('idx_xg_player_gw', table_name='player_gw_xg')
    op.drop_table('player_gw_xg')
    op.drop_index('idx_pgw_player_gw', table_name='player_gw_stats')
    op.drop_index('idx_pgw_gw', table_name='player_gw_stats')
    op.drop_table('player_gw_stats')
    op.drop_index('idx_form_player', table_name='player_form_cache')
    op.drop_table('player_form_cache')
    op.drop_table('players')
    op.drop_index('idx_fixtures_gw', table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_table('teams')
    op.drop_table('gameweeks')
    # ### end Alembic commands ###
