"""add query performance indexes

Revision ID: b08a00b1c327
Revises: 9945ad542039
Create Date: 2026-03-31 09:25:20.199356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08a00b1c327'
down_revision: Union[str, Sequence[str], None] = '9945ad542039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_fixtures_away_team', 'fixtures', ['away_team_id'], unique=False)
    op.create_index('idx_fixtures_finished_gw', 'fixtures', ['finished', 'gameweek_id'], unique=False)
    op.create_index('idx_fixtures_home_team', 'fixtures', ['home_team_id'], unique=False)
    op.create_index('idx_players_status', 'players', ['status'], unique=False)
    op.create_index('idx_players_team_position', 'players', ['team_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_players_team_position', table_name='players')
    op.drop_index('idx_players_status', table_name='players')
    op.drop_index('idx_fixtures_home_team', table_name='fixtures')
    op.drop_index('idx_fixtures_finished_gw', table_name='fixtures')
    op.drop_index('idx_fixtures_away_team', table_name='fixtures')
    # ### end Alembic commands ###
