"""add unique constraints for upserts

Revision ID: fb7e8c7601cf
Revises: ae6f98875242
Create Date: 2026-03-26 10:20:56.327801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7e8c7601cf'
down_revision: Union[str, Sequence[str], None] = 'ae6f98875242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_pgw_player_gw_fixture', 'player_gw_stats', ['player_id', 'gameweek_id', 'fixture_id'])
    op.create_unique_constraint('uq_prices_player_date', 'player_prices', ['player_id', 'recorded_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prices_player_date', 'player_prices', type_='unique')
    op.drop_constraint('uq_pgw_player_gw_fixture', 'player_gw_stats', type_='unique')
    # ### end Alembic commands ###
